# Site settings
title: RenArtDB
email: carlo.corsato@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://localhost:4000"
twitter_username: CarloCorsato
github_username:  carlocorsato


# Build settings
kramdown:
  input: GFM
permalink: pretty
